database:
  image: "sameersbn/postgresql:9.4-12"
  environment:
    DB_NAME: "taiga"
    DB_USER: "taiga"
    DB_PASS: "taiga"
  volumes:
    - "/opt/docker/taiga/postgresql/data:/var/lib/postgresql:rw"
rabbitmq:
  image: "rabbitmq:3.5.5"
  hostname: taiga-rabbit
  restart: always
  environment:
    RABBITMQ_DEFAULT_USER: "taiga"
    RABBITMQ_DEFAULT_PASS: "taiga"
redis:
  image: "quay.io/sameersbn/redis:latest"
  volumes:
    - "/opt/docker/taiga/redis:/var/lib/redis:rw"
taiga:
  image: "quay.io/galexrt/taiga:latest"
  ports:
    - "80:80"
    - "443:443"
    - "8888:8888"
  links:
    - database
    - rabbitmq
    - redis
  environment:
    DB_HOST: "database_1"
    DB_NAME: "taiga"
    DB_USER: "taiga"
    DB_PASS: "taiga"
    RABBITMQ_HOST: "rabbitmq_1"
    RABBITMQ_USER: "taiga"
    RABBITMQ_PASS: "taiga"
    REDIS_HOST: "redis_1"
    ADMIN_USERS: "(\"Admin 1\",\"admin1@example.com\");(\"Admin 2\",\"admin2@example.com\")"
    SETTING_SECRET_KEY: "YOUR_OWN_SECRET_KEY"
    SETTING_PUBLIC_REGISTER_ENABLED: "True"
    SETTING_GITHUB_API_CLIENT_ID: ""
    SETTING_GITHUB_API_CLIENT_SECRET: ""
    INSERT_DEFAULT_DATA: "True"
